// export const emailLink = "mailto:info@arabsinneuro.org";
export const emailName = "info@arabsinneuro.org";
export const facebookLink = "https://www.facebook.com/ArabsInNeuro";
export const facebookName = "ArabsInNeuro";
export const instagramLink = "https://instagram.com/arabsineuro";
export const instagramName = "arabsineuro";
export const twiterLink = "https://twitter.com/ArabsInNeuro";
export const twiterName = "ArabsInNeuro";
export const linkedinLink = "https://www.linkedin.com/company/arabs-in-neuroscience-ain/mycompany/";
export const linkedinName = "arabs-in-neuroscience-ain";
export const studentsApplicationLink = "https://docs.google.com/forms/d/e/1FAIpQLSdfGwumYEbxU00hqHEzT-rcKLyuW3DFdAZrAjbsZDN62HGnVA/viewform?usp=sf_link";
export const taApplicationLink = "https://docs.google.com/forms/d/e/1FAIpQLSfdY4xzPBvbEis_fhNUAj_L8NODBGU8ZqtnMgNb2PGQG2cgyg/viewform?usp=sf_link";
export const eegSchoolApplicationLink = "https://docs.google.com/forms/d/1A9I--APy-pGoRRgWeTQ_9T-LJMKF_Lpdw3bg7BYZSkI/edit";